### ISSUE TITLE
Destructuring throws syntax error

### ISSUE THREAD

**Issue by evanrs** [renke/atom-import-sort#12]
The following results in a syntax error:
```js
let a, b;
{ a, b } = { a: 1, b: 2 };
```

Is it fair to expect compatibility with [babel-preset-latest](http://babeljs.io/docs/plugins/preset-latest/)?

**Comment by renke** [comment]
Mh, I would expect that not to throw an error. I try to look into that in the next week. Thanks for reporting this issue.

**Comment by renke** [comment]
Hi @evanrs,

it seems like that is not valid syntax for Babylon. You can test it yourself here: https://babeljs.io/repl/ 

`let a, b = { a: 1, b: 2 };` works though.

I am closing this issue for now.
