### ISSUE TITLE
What about sorting exports?

### ISSUE THREAD

**Issue by rohan-deshpande** [renke/atom-import-sort#14]
Might be a nice feature to have you could sort by name first and then source file?

**Comment by renke** [comment]
Hi @rohan-deshpande 

sorting exports is a bit harder because the order of which sometimes matters. Definitely nice to have, but out of scope of this project in my opinion.

Thanks for the suggestion though!

**Comment by rohan-deshpande** [comment]
Order of exports matters? Really? Not doubting but can you give an example? Never thought the export order would matter. Anyway all good! I'm just using `atom-sort-list` for now, basically does what I wanted anyways :)

**Comment by renke** [comment]
Hi @rohan-deshpande 

maybe we meant something differnt, but consider this piece of code and imagine what would happen if we order the exports (bar first, foo second). 

```js
export const foo = "world";
export const bar = "hello" + foo;

console.log(bar);
```

I only tested it with babel-cli, though.

However, if you mean sorting named members like `export { foo, bar };`, that might be useful.

**Comment by rohan-deshpande** [comment]
Hmm ok, I mean seems like pretty bad practice to do that with exports though, a little confusing, a better pattern would be to import `foo` into `bar` and then export the result from there, but yes I can see that people would do it. However, if you did sort them alphabetically, `eslint` would also report an error in that case if `no-use-before-define` was enabled. 

I do see your point though.
