### ISSUE TITLE
does not work with linter-eslint

### ISSUE THREAD

**Issue by trshafer** [renke/atom-import-sort#2]
https://atom.io/packages/linter-eslint provides helpful lint errors such as:
<img width="342" alt="screen shot 2016-01-28 at 2 00 22 pm" src="https://cloud.githubusercontent.com/assets/135461/12660221/87bed1fa-c5c7-11e5-84dd-f7fcedf410c3.png">

with atom-import-sort disabled I get helpful lint errors such as:
<img width="339" alt="screen shot 2016-01-28 at 2 01 32 pm" src="https://cloud.githubusercontent.com/assets/135461/12660252/ad31a14c-c5c7-11e5-8902-838225abbec9.png">

but with atom-import-sort enabled the lines are no longer visible and just looks like: 
<img width="344" alt="screen shot 2016-01-28 at 2 02 25 pm" src="https://cloud.githubusercontent.com/assets/135461/12660277/cbc723d4-c5c7-11e5-9feb-81975785847e.png">

I have sort on save turned on. It appears to work until I save and then the lint error lines go away.

Thanks! Great and helpful package.

**Comment by growlsworth** [comment]
I have turned off sort on save. The linter works again, but when I use "Import Sort: Sort" the lint errors go away.

**Comment by renke** [comment]
I noticed this in other situations (unrelated to atom-import-sort), too. I think changing tabs (or similar actions) will show the linter errors again. I am not too sure I can fix that in atom-import-sort to be honest. I will close it for now and I hope it doesn't bug you too much!

**Comment by thomasjshafer** [comment]
Thanks for taking a look. I'll see if I can open a dialog on the linter. The package works great by the way. Makes the top of the file much easier to read.

**Comment by thomasjshafer** [comment]
Looks like recent updates to atom have fixed this. Don't know where the fix came from but this issue is now resolved. It works with "sort on save" turned on as well.

**Comment by thomasjshafer** [comment]
I lied. It's still broken when there is nothing to change. If the text comes back the same, the linter disappears. If the sort order changes, the linter will reappear. The sort order does not change most of the time, so it's still broken unfortunately. Wanted to post an update, but looks like it's still an issue.

**Comment by pencil001** [comment]
I also meet this bug. 

@renke you should reopen this issue.

**Comment by renke** [comment]
I will look into this for the next release.

**Comment by renke** [comment]
Small update: I think the new version of `atom-import-sort` improves this situation, but it's not perfect yet. Still trying to find a way to completely fix it.

**Comment by pencil001** [comment]
I have tried it. It is better now though not perfect. Thank you.
