### ISSUE TITLE
Support webpack aliases

### ISSUE THREAD

**Issue by tuckerconnelly** [renke/atom-import-sort#3]
Yo! Thank you for making this :D

We use webpack aliases in our project, so 

`import MyComponent from 'components/myfolder/MyComponent'` instead of
`import MyComponent from '../myfolder/MyComponent'`

Would be nice if we could configure them to go in the "local" list :)

**Comment by renke** [comment]
Hi @tuckerconnelly, 

glad you find the plugin useful. Regarding your problem, technically it should not be hard to implement this (e.g. by having a list of "local" directory like "components" in your case) but there is currently no way to change the default style in atom-import-sort (preferably per-project). See https://github.com/renke/import-sort/issues/3#issuecomment-169111198 for a proposed solution. I hope I find some time next week to implement that idea.

**Comment by renke** [comment]
It's now possible to write and use custom styles. See [`import-sort`](https://github.com/renke/import-sort) for more information.

**Comment by fsmaia** [comment]
Hi! I have few available time and even fewer TypeScript experience, but today I just started something here: https://github.com/fsmaia/import-sort-style-module-relative-aliases.

I can see two possibilities to remove those hardcoded aliases:
a) By reading webpack.config.js `alias` Object keys from current working directory (it would be necessary to test in both Atom and VSCode)
b) By modifying `import-sort` to allow a additional custom configuration object and receiving it by parameter in [this function](https://github.com/fsmaia/import-sort-style-module-relative-aliases/blob/master/src/index.ts#L20)
