### ISSUE TITLE
On selection sort

### ISSUE THREAD

**Issue by alansouzati** [renke/atom-import-sort#4]
Thanks for working on this useful plugin. Do you think there is value on adding `on selection` sort?

  Sometimes I like to have few core dependencies on top of my JS file and only sort a given group of imports.

  When I selected the group of imports and pressed `control + alt + o` I was expecting the sorting to affect only these elements.

  I believe this should not be difficult to add to your plugin. If you agree with this change I'm willing to write a PR for that.

**Comment by renke** [comment]
I agree that can be useful in certain situations. So, yeah, go ahead ;)
