### ISSUE TITLE
Sorting unfolds folded blocks

### ISSUE THREAD

**Issue by awestroke** [renke/atom-import-sort#5]
If you fold code and then apply import sort, everything is unfolded again. See attached gif

![import-sort-unfolding](https://cloud.githubusercontent.com/assets/1098408/13137328/8a472918-d620-11e5-86a7-fa5c5ec10101.gif)

**Comment by renke** [comment]
Mh, yes, I think it happens because I replace the whole content of the text buffer. Maybe we could be smart only replace the area that contained the imports. Doing this would probably also resolve https://github.com/renke/atom-import-sort/issues/6

**Comment by renke** [comment]
This should be fixed in the new version of `atom-import-sort`.

**Comment by awestroke** [comment]
:+1:
