### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by chadaustin** [renke/atom-import-sort#6]
We converted our project from Babel/ES6 to TypeScript, but we still use ES6-style imports.  It would be great if this plugin could sort TypeScript imports too.

**Comment by renke** [comment]
Mh, Babel can't parse TypeScript (as far as I know), but I think the the plugin could just try to only parse the "header" of a file. Probably based on some kind of heuristic. Thoughts?

**Comment by chadaustin** [comment]
Perhaps!  Or it could support the TypeScript parser too, if such a thing is conveniently accessible?

**Comment by renke** [comment]
Hi there, sorry for the late answer! The next release will include support for TypeScript! Soon to come!

**Comment by renke** [comment]
I just wanted to say that the new version of `atom-import-sort` includes support for TypeScript. Let me know if it works for you!
