### ISSUE TITLE
Inline comments are placed after the import blocks

### ISSUE THREAD

**Issue by marlonpp** [renke/atom-import-sort#7]
Sometimes to avoid some lint errors it's needed to place an inline comment after the import, for example:

```js
import SomeThing from './components/some/SomeThing'; //eslint-disable-inline import/no-named-as-default
import someOtherThing from './someOtherThing';
```

After applying the sort, it becomes:

```js
import SomeThing from './components/some/SomeThing'; 
import someOtherThing from './someOtherThing';

//eslint-disable-inline import/no-named-as-default
```

Making it not possible to disable the lint.

**Comment by renke** [comment]
Hi there, I am aware of this problem. This has top priority for the next
release. Promised!

**Comment by renke** [comment]
This should now be fixed in the new version of `atom-import-sort`!
