### ISSUE TITLE
Absolute imports should come before relative imports

### ISSUE THREAD

**Issue by screendriver** [renke/atom-import-sort#8]
I'm getting this error from ESLint because [this rule](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/imports-first.md) complains my import order.

Unfortunately `atom-import-sort` does not sort this way.

**Comment by renke** [comment]
Hi there, I am currently working on the next version of import-sort and
atom-import-sort which will come with a eslint style that conforms to the
corresponding eslint rule. Stay tuned!

**Comment by renke** [comment]
I released a new version of `atom-import-sort` which not by default sorts imports such that they conform to ESLint's [sort-imports](http://eslint.org/docs/rules/sort-imports) rule. I am not sure if that solves your problem. If it doesn't, you can now pretty easily write your own custom style.

**Comment by screendriver** [comment]
Thank you for the update. Now I'm getting following error: `Failed to sort imports: TypeError: import_sort_1.default is not a function`

**Comment by renke** [comment]
Can you try to re-install atom-import-sort? – Maybe the old import-sort package is still installed.

**Comment by screendriver** [comment]
I installed your latest update and now it seems to work.

**Comment by cyrilepinat** [comment]
Hi there, maybe I'm missing something, but I'm using atom-import-sort and sort is not done following import/first (absolute-first) rule. Any help would be awesome ! Thanks !
my versions:
atom-import-sort v2.4.0
linter-eslint v8.1.2
eslint v3.15.0
