### ISSUE TITLE
Incompatible with object-curly-spacing settings from eslint

### ISSUE THREAD

**Issue by hellpf** [renke/atom-import-sort#9]
After the last update there was changed behavior and once it is sorted, spaces after { and before } are removed. We use http://eslint.org/docs/rules/object-curly-spacing
> "object-curly-spacing": [2, "always"].

Before save:
> import React, { Component } from 'react';

After save:
> import React, {Component} from 'react';

It is possible to respect eslint settings? Or add this setting to the atom.io plugin?

**Comment by renke** [comment]
Oh, I didn't think about that. Sorting named members is trickier than expected. I don't want to parse ESLint's config, but perhaps an auto-detection would work. That is, when a space after (or before) the `{` (or `}`) is detected, it will keep those spaces. Would that work for you?

I am going to try to fix it tomorrow or the day after.

**Comment by hellpf** [comment]
Yes the auto-detection would be great!

**Comment by renke** [comment]
I added this feature to the new release. Let me know if it works for your!

**Comment by hellpf** [comment]
It works great! Thx!
